import React from 'react';
import ReactDOM from 'react-dom';

import './assets/js/main.min.js';
import './assets/js/staticman/staticman-reviews.js';
import './assets/js/vendor/real-time/WebPushManager.js';

import App from './components/App';

ReactDOM.render(<App />, document.getElementById('app'));

var Worker = require("worker-loader?name=hash.worker.js!./worker");
var worker = new Worker();
worker.postMessage("pageB");
worker.onmessage = function(event) {
	var templatepageB = event.data; // "This text was generated by template pageB"
};
