import React, { Component } from "react";

class App extends Component {
  render() {
    return (
      <div>Hey, y’all!! This is a react component.</div>
    )
  }
}
export default App;

var jquery = require('./jquery-3.3.1.slim.min.js');
var main = require('./main.min.js');
var comments = require('./staticman.comments.min.js');
var fileupload = require('./file-upload-with-preview.min.js');
var reviews = require('./staticman.reviews.min.js');
var pjax = require("jquery-pjax");
var passiveevents = require('default-passive-events');

var Worker = require("worker-loader?name=hash.worker.js!./worker");
var worker = new Worker();
worker.postMessage("pageB");
worker.onmessage = function(event) {
	var templatepageB = event.data; // "This text was generated by template pageB"
};

