import React, { Component } from "react";

class App extends Component {
  render() {
    return (
      <div>Hey, y’all!! This is a react component.</div>
    )
  }
}
export default App;

var Worker = require("worker-loader?name=hash.worker.js!./worker");
var worker = new Worker();
worker.postMessage("pageB");
worker.onmessage = function(event) {
	var templatepageB = event.data; // "This text was generated by template pageB"
};

